<h2>monthly Report ({{ $startOfMonth->format('Y-m-d') }} - {{ $endOfMonth->format('Y-m-d') }})</h2>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Status</th>
            <th>Generated By</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>
        @forelse($reports as $report)
            <tr>
                <td>{{ $report->title }}</td>
                <td>{{ $report->description }}</td>
                <td>{{ $report->status }}</td>
                <td>{{ optional($report->user)->name }}</td>
                <td>{{ $report->created_at->format('Y-m-d') }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="5">No reports found for this monthly.</td>
            </tr>
        @endforelse
    </tbody>
</table>
