<!-- resources/views/reports/show.blade.php -->

@extends('layouts.app')

@section('title', 'Report Details')

@section('content')
<div class="container">
    <h1 class="my-4">Report Details</h1>

   
    <div>
        <h3>{{ $report->title }}</h3>
        <p><strong>Status:</strong> 
            @if($report->status == 'approved')
                <span class="badge bg-success text-light">Approved</span>
            @elseif($report->status == 'rejected')
                <span class="badge bg-danger text-light">Rejected</span>
            @else
                <span class="badge bg-warning text-dark">Pending</span>
            @endif
        </p>
        <p><strong>Created At:</strong> {{ $report->created_at->format('Y-m-d') }}</p>
        <p><strong>Document:</strong> {{ optional($report->document)->title ?? 'N/A' }}</p>
        <p><strong>Generated By:</strong> {{ optional($report->generatedBy)->name ?? 'Unknown' }}</p>

        <a href="{{ route('reportsOverview') }}" class="btn btn-primary mt-4">Back to Reports</a>
    </div>
</div>
@endsection
